micronaut:
  application:
    name: hm-grunndata-index
    thread-selection: auto
  executors:
    consumer:
      type: fixed
      nThreads: 1
  http:
    client:
      max-content-length: 100833718
      read-timeout: "5m"
      event-loop-group: http
  netty:
    event-loops:
      http:
        num-threads: 10
        prefer-native-transport: true
  server:
    max-request-size: 100833718
    port: ${SERVER_PORT:8080}
  data:
    pageable:
      max-page-size: 5000
  metrics:
    enabled: true
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
      jdbc:
        enabled: true
      kafka:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

opensearch:
  password: ${OPEN_SEARCH_PASSWORD:admin}
  user: ${OPEN_SEARCH_USERNAME:admin}
  url: ${OPEN_SEARCH_URI:`https://localhost:9200`}

hmdb:
  url: ${HMDB_URL:`http://localhost:8081`}

# Rapids and rivers config
rapidsandrivers:
  enabled: ${RAPIDSANDRIVERS_ENABLED:false}

kafka:
  topic: teamdigihot.hm-grunndata-v1
  consumerGroupId: hm-grunndata-index-g1
  trustStorePath: ${KAFKA_TRUSTSTORE_PATH:}
  trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  keystorePath: ${KAFKA_KEYSTORE_PATH:}
  keystorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  health:
    enabled: false

agreements:
  aliasName: ${AGREEMENTS_ALIASNAME:agreements}
external_products:
  aliasName: ${EXTERNAL_PRODUCTS_ALIASNAME:external_products}
suppliers:
  aliasName: ${SUPPLIERS_ALIASNAME:suppliers}
products:
  aliasName: ${PRODUCTS_ALIASNAME:products}
news:
  aliasName: ${NEWS_ALIASNAME:news}
alternative_products:
  aliasName: ${ALTERNATIVE_PRODUCTS_ALIASNAME:alternative_products}

grunndata:
  db:
    url: ${GRUNNDATA_DB_URL:`http://localhost:8888`}
  register:
    url: ${GRUNNDATA_REGISTER_URL:`http://localhost:7777/admreg`}
  alternativprodukter:
    url: ${GRUNNDATA_ALTERNATIVPRODUKTER_URL:`http://localhost:5555`}

elector:
  path: ${ELECTOR_PATH:localhost}