name: deploy-rollback
on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'What cluster?'
        required: true
        default: 'dev-gcp'
        type: choice
        options:
          - dev-gcp
          - prod-gcp
      version:
        description: 'What version?'
        required: true
        type: string
      team:
        description: 'What team?'
        required: true
        default: teamdigihot
        type: string
env:
  VERSION_TAG: ${{ inputs.version }}
  CLUSTER: ${{ inputs.cluster }}
  IMAGE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/${{inputs.team}}/${{ github.event.repository.name }}:${{ inputs.version }}
jobs:
  deploy-direct:
    permissions:
      contents: write
      id-token: write
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.VERSION_TAG }}
      - uses: nais/deploy/actions/deploy@v2
        name: deploy to ${{ inputs.cluster }}
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .nais/nais.yml
          VARS: .nais/nais_${{ inputs.cluster }}.json
